# Generated by Django 5.1.6 on 2025-03-10 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llama_processor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_text', models.TextField()),
                ('order', models.IntegerField()),
                ('text_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='llama_processor.textentry')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='text_chunk',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='llama_processor.textchunk'),
        ),
    ]
