# Generated by Django 5.1.6 on 2025-03-10 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llama_processor', '0002_textchunk_question_text_chunk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='text_entry',
        ),
        migrations.AlterField(
            model_name='question',
            name='text_chunk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='llama_processor.textchunk'),
        ),
    ]
