# Generated by Django 5.1.6 on 2025-03-10 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llama_processor', '0003_remove_question_text_entry_alter_question_text_chunk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='llama_processor.question'),
        ),
        migrations.AlterUniqueTogether(
            name='textchunk',
            unique_together={('text_entry', 'order')},
        ),
    ]
