# Generated by Django 5.1.6 on 2025-03-10 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llama_processor', '0004_alter_answer_question_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='textchunk',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='answers', to='llama_processor.question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text_chunk',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='llama_processor.textchunk'),
        ),
    ]
