GRANT EXECUTE ANY PROCEDURE TO LAB3;
GRANT EXECUTE ANY PROCEDURE ON SCHEMA DEV TO LAB3;
GRANT EXECUTE ANY PROCEDURE ON SCHEMA PROD TO SYSTEM;
GRANT SELECT ANY TABLE TO LAB3;
GRANT SELECT ANY TABLE ON SCHEMA DEV TO LAB3;
GRANT SELECT ANY TABLE ON SCHEMA PROD TO LAB3;
GRANT SELECT ANY DICTIONARY TO LAB3;
ALTER USER LAB3 QUOTA UNLIMITED ON USERS;
-- Предоставляем права на select и execute к словарям данных
GRANT SELECT_CATALOG_ROLE TO LAB3;
GRANT EXECUTE_CATALOG_ROLE TO LAB3;

GRANT SELECT_CATALOG_ROLE TO FUNCTION create_object;
GRANT SELECT_CATALOG_ROLE TO FUNCTION update_object;