DROP SEQUENCE STUDENTS_SEQ;
DROP SEQUENCE GROUPS_SEQ;

CREATE SEQUENCE STUDENTS_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE GROUPS_SEQ START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER STUDENTS_INCREMENT_ID
BEFORE INSERT ON STUDENTS
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        SELECT STUDENTS_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER GROUPS_INCREMENT_ID
BEFORE INSERT ON GROUPS
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        SELECT GROUPS_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER GROUPS_UNIQUE_ID
BEFORE INSERT OR UPDATE ON GROUPS
FOR EACH ROW
DECLARE
    v_count NUMBER;
BEGIN
    IF NOT group_management.is_updating_count THEN
        SELECT COUNT(*) INTO v_count FROM GROUPS WHERE NAME = :NEW.NAME AND ID != :NEW.ID;
        IF v_count > 0 THEN
            RAISE_APPLICATION_ERROR(-20001, 'Group name must be unique.');
        END IF;
    END IF;
END;
/