DELETE FROM GROUPS;

INSERT INTO GROUPS (ID, NAME) VALUES ('Group A');
INSERT INTO GROUPS (ID, NAME) VALUES ('Group B');

INSERT INTO STUDENTS (NAME, GROUP_ID) VALUES ('Ivan Ivanov', 1);
INSERT INTO STUDENTS (NAME, GROUP_ID) VALUES ('Petr Petrov', 1);
INSERT INTO STUDENTS (NAME, GROUP_ID) VALUES ('Sidor Sidorov', 2);

SELECT * FROM GROUPS;
SELECT * FROM STUDENTS;

DELETE FROM STUDENTS WHERE ID=1;

SELECT * FROM STUDENTS_LOG;

INSERT INTO STUDENTS (NAME, GROUP_ID) VALUES ('TEST TEST', 2);
DELETE FROM STUDENTS WHERE ID=4;

DECLARE
    v_restore_time TIMESTAMP := TO_TIMESTAMP('2025-02-19 16:54:44', 'YYYY-MM-DD HH24:MI:SS');
BEGIN
    RESTORE_STUDENTS(v_restore_time);
END;
/

DECLARE
    v_restore_time TIMESTAMP := TO_TIMESTAMP('2023-10-01 10:00:00', 'YYYY-MM-DD HH24:MI:SS');
    v_time_offset INTERVAL DAY TO SECOND := INTERVAL '1' HOUR;
BEGIN
    RESTORE_STUDENTS(v_restore_time, v_time_offset);
END;
/