CREATE TABLE "GROUPS" 
   (  
   "ID" NUMBER NOT NULL ENABLE, 
   "NAME" VARCHAR2(50) NOT NULL ENABLE, 
   "C_VAL" NUMBER,
   CONSTRAINT "PK_GROUPS" PRIMARY KEY ("ID")
  );
  
CREATE TABLE "STUDENT_LOG" 
   (  
   "LOG_ID" NUMBER, 
  "ACTION_TYPE" VARCHAR2(10) NOT NULL ENABLE, 
  "STUDENT_ID" NUMBER, 
  "STUDENT_NAME" VARCHAR2(50), 
  "GROUP_ID" NUMBER, 
  "ACTION_TIME" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
  "GROUP_NAME" VARCHAR2(100), 
   PRIMARY KEY ("LOG_ID")
   );
   
CREATE TABLE "STUDENTS" 
   (  
  "ID" NUMBER NOT NULL ENABLE, 
  "NAME" VARCHAR2(50) NOT NULL ENABLE, 
  "GROUP_ID" NUMBER,
  CONSTRAINT "PK_STUDENTS" PRIMARY KEY ("ID")
   );
